# Generated by Django 5.0.6 on 2026-06-01 13:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('source_module', models.CharField(max_length=100)),
                ('aggregation_method', models.CharField(help_text='count | sum | avg | max | min', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'analytics_reporting_metric',
            },
        ),
        migrations.CreateModel(
            name='ActivitySummaryReportingWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('delivery_failed', 'Delivery Failed'), ('superseded', 'Superseded'), ('suppressed_no_activity', 'Suppressed (No Activity)')], default='active', max_length=30)),
                ('effective_start', models.DateTimeField(help_text='Earliest start of this + all subsumed windows')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('subsumed_by_window', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subsumed_windows', to='analytics.activitysummaryreportingwindow')),
            ],
            options={
                'db_table': 'analytics_summary_reporting_window',
            },
        ),
        migrations.CreateModel(
            name='ActivitySummaryAggregationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('source_fact_references', models.JSONField(default=list, help_text='List of source event/record references consumed in this aggregation')),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('shipments_count', models.PositiveIntegerField(default=0)),
                ('sla_exceptions_count', models.PositiveIntegerField(default=0)),
                ('late_imports_count', models.PositiveIntegerField(default=0)),
                ('missing_imports_count', models.PositiveIntegerField(default=0)),
                ('partial_imports_count', models.PositiveIntegerField(default=0)),
                ('result_discriminator', models.CharField(help_text='has_activity | suppressed_no_activity', max_length=50)),
                ('aggregated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aggregation_records', to='analytics.activitysummaryreportingwindow')),
            ],
            options={
                'db_table': 'analytics_summary_aggregation_record',
            },
        ),
        migrations.CreateModel(
            name='DataFreshnessMarker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_module', models.CharField(db_index=True, max_length=100)),
                ('source_event_type', models.CharField(blank=True, max_length=200)),
                ('last_processed_at', models.DateTimeField()),
                ('last_source_record_reference', models.UUIDField(blank=True, null=True)),
                ('is_stale', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_data_freshness',
                'unique_together': {('source_module', 'source_event_type')},
            },
        ),
        migrations.AddIndex(
            model_name='activitysummaryreportingwindow',
            index=models.Index(fields=['status', 'window_start'], name='analytics_s_status_05a908_idx'),
        ),
    ]
