# Generated by Django 5.0.6 on 2026-06-01 13:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_scope_reference', models.UUIDField(db_index=True)),
                ('invoice_type', models.CharField(choices=[('buyer_invoice', 'Buyer Invoice'), ('vendor_statement', 'Vendor Statement'), ('vendor_payable_package', 'Vendor Payable Package'), ('commission_report', 'Commission Report'), ('adjustment_report', 'Adjustment Report'), ('internal_admin_invoice_report', 'Internal Admin Invoice Report')], max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_validation', 'Pending Validation'), ('validation_failed', 'Validation Failed'), ('ready', 'Ready'), ('issued', 'Issued'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('disputed', 'Disputed'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('void', 'Void'), ('superseded', 'Superseded'), ('archived', 'Archived')], default='draft', max_length=30)),
                ('counterparty_role', models.CharField(help_text='buyer | vendor', max_length=20)),
                ('counterparty_reference', models.UUIDField(db_index=True)),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=14)),
                ('commission_total', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('adjustment_total', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=4, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('quickbooks_handoff_request_reference', models.UUIDField(blank=True, null=True)),
                ('quickbooks_payment_status_reference', models.CharField(blank=True, help_text='QuickBooks payment status returned — NOT CIXCI-owned payment truth', max_length=100)),
                ('auto_payment_submitted', models.BooleanField(default=False, help_text='ALWAYS False in Phase 1. Core no-auto-payment rule: CIXCI does not automatically submit vendor payment.')),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'invoice_invoice',
            },
        ),
        migrations.CreateModel(
            name='InvoicePeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_scope_reference', models.UUIDField(db_index=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('channel', models.CharField(blank=True, max_length=30)),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'invoice_period',
            },
        ),
        migrations.CreateModel(
            name='InvoiceRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('queued', 'Queued'), ('initializing', 'Initializing'), ('running', 'Running'), ('paused', 'Paused'), ('validation_failed', 'Validation Failed'), ('partially_complete', 'Partially Complete'), ('complete', 'Complete'), ('superseded', 'Superseded'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back'), ('pending_review', 'Pending Review'), ('archived', 'Archived')], default='draft', max_length=30)),
                ('company_scope_reference', models.UUIDField(db_index=True)),
                ('run_label', models.CharField(blank=True, max_length=200)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True)),
                ('created_by', models.UUIDField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'invoice_run',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(db_index=True, help_text='hash(period_id, counterparty_reference, source_order_line_reference)', max_length=512)),
                ('source_module', models.CharField(max_length=100)),
                ('source_order_line_reference', models.UUIDField(db_index=True)),
                ('source_product_reference', models.UUIDField(blank=True, null=True)),
                ('source_pricing_snapshot_reference', models.UUIDField(help_text='EffectivePriceSnapshot ID — snapshot evidence; not a live FK')),
                ('source_fulfillment_evidence_reference', models.UUIDField(blank=True, null=True)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=4, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('line_total', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('line_description', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='invoicing.invoice')),
            ],
            options={
                'db_table': 'invoice_line',
                'unique_together': {('invoice', 'idempotency_key')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_kind', models.CharField(help_text='refund | credit | debit | fee_adjustment | commission_correction | late_return_credit | write_off | other', max_length=50)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('reason', models.TextField()),
                ('evidence_reference', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='invoicing.invoice')),
                ('original_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoicing.invoiceline')),
            ],
            options={
                'db_table': 'invoice_adjustment',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoicing.invoiceperiod'),
        ),
        migrations.CreateModel(
            name='InvoiceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(help_text='summary | vendor_breakdown | buyer_breakdown | exception_log | audit_trail', max_length=50)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_reference', models.UUIDField(blank=True, null=True)),
                ('company_scope_reference', models.UUIDField(db_index=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='invoicing.invoicerun')),
            ],
            options={
                'db_table': 'invoice_report',
            },
        ),
        migrations.AddField(
            model_name='invoiceperiod',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='invoicing.invoicerun'),
        ),
        migrations.CreateModel(
            name='InvoiceExceptionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exception_kind', models.CharField(help_text='e.g. missing_delivery_evidence | pricing_snapshot_expired | duplicate_line | eligibility_failed', max_length=80)),
                ('description', models.TextField()),
                ('source_reference', models.UUIDField(blank=True, null=True)),
                ('is_blocking', models.BooleanField(default=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoicing.invoice')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='invoicing.invoicerun')),
            ],
            options={
                'db_table': 'invoice_exception_record',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoicing.invoicerun'),
        ),
        migrations.CreateModel(
            name='VendorReconciliationUploadJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_company_reference', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('received', 'Received'), ('parsing', 'Parsing'), ('parse_failed', 'Parse Failed'), ('validating', 'Validating'), ('validation_failed', 'Validation Failed'), ('matching', 'Matching'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('file_reference', models.UUIDField(blank=True, null=True)),
                ('file_tracking_reference', models.UUIDField(blank=True, null=True)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('matched_count', models.PositiveIntegerField(blank=True, null=True)),
                ('unmatched_count', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_jobs', to='invoicing.invoice')),
            ],
            options={
                'db_table': 'invoice_reconciliation_upload_job',
            },
        ),
        migrations.CreateModel(
            name='VendorReconciliationMatchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_result_status', models.CharField(choices=[('matched', 'Matched'), ('matched_with_variance', 'Matched with Variance'), ('unmatched_cixci_only', 'Unmatched — CIXCI Only'), ('unmatched_vendor_only', 'Unmatched — Vendor Only'), ('disputed', 'Disputed'), ('pending_review', 'Pending Review'), ('override_accepted', 'Override Accepted'), ('override_rejected', 'Override Rejected'), ('resolved', 'Resolved'), ('partial_match', 'Partial Match'), ('excluded', 'Excluded'), ('escalated', 'Escalated'), ('archived', 'Archived')], max_length=30)),
                ('cixci_line_total', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('vendor_reported_total', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('vendor_line_reference', models.CharField(blank=True, max_length=255)),
                ('variance_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_by', models.UUIDField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoicing.invoiceline')),
                ('upload_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_results', to='invoicing.vendorreconciliationuploadjob')),
            ],
            options={
                'db_table': 'invoice_reconciliation_match_result',
            },
        ),
        migrations.AddIndex(
            model_name='invoiceperiod',
            index=models.Index(fields=['company_scope_reference', 'period_start', 'is_closed'], name='invoice_per_company_069e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceexceptionrecord',
            index=models.Index(fields=['run', 'is_blocking', 'resolved'], name='invoice_exc_run_id_7f7a62_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company_scope_reference', 'status', 'invoice_type'], name='invoice_inv_company_ce945c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['counterparty_reference', 'status'], name='invoice_inv_counter_2cfdc4_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorreconciliationuploadjob',
            index=models.Index(fields=['vendor_company_reference', 'status'], name='invoice_rec_vendor__b6fd67_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorreconciliationmatchresult',
            index=models.Index(fields=['upload_job', 'match_result_status'], name='invoice_rec_upload__1ca952_idx'),
        ),
    ]
