# Generated by Django 5.0.6 on 2026-06-01 13:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_scope_reference', models.UUIDField(db_index=True)),
                ('buyer_reference', models.UUIDField(db_index=True)),
                ('vendor_company_reference', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('submitted', 'Submitted'), ('acknowledged', 'Acknowledged'), ('partially_fulfilled', 'Partially Fulfilled'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('dispute', 'Dispute'), ('closed', 'Closed')], default='draft', max_length=30)),
                ('pricing_snapshot_reference', models.UUIDField(blank=True, help_text='EffectivePriceSnapshot ID from Pricing module — read-only reference', null=True)),
                ('po_number', models.CharField(blank=True, max_length=200)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'procurement_purchase_order',
                'indexes': [models.Index(fields=['company_scope_reference', 'status'], name='procurement_company_58b02a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_reference', models.UUIDField(db_index=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price_snapshot', models.DecimalField(decimal_places=4, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=4, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='procurement.purchaseorder')),
            ],
            options={
                'db_table': 'procurement_purchase_order_line',
            },
        ),
    ]
