# Generated by Django 5.0.6 on 2026-06-01 13:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorExportDeliveryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('delivery_method', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(help_text='in_progress | succeeded | failed | timed_out', max_length=30)),
                ('error_detail', models.TextField(blank=True)),
                ('provider_reference', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'routing_vendor_export_delivery_attempt',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_scope_reference', models.UUIDField(db_index=True)),
                ('buyer_reference', models.UUIDField(db_index=True)),
                ('buyer_entity_reference', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('routed', 'Routed'), ('partially_routed', 'Partially Routed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('pricing_snapshot_references', models.JSONField(default=dict, help_text='product_id → EffectivePriceSnapshot ID mapping')),
                ('placed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'routing_order',
                'indexes': [models.Index(fields=['company_scope_reference', 'status'], name='routing_ord_company_dac7a8_idx'), models.Index(fields=['buyer_reference', 'placed_at'], name='routing_ord_buyer_r_497e9f_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoutedSuborder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_company_reference', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('routed', 'Routed'), ('partially_routed', 'Partially Routed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('routing_snapshot', models.JSONField(default=dict, help_text='Routing decision snapshot at creation')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routed_suborders', to='routing.order')),
            ],
            options={
                'db_table': 'routing_routed_suborder',
            },
        ),
        migrations.CreateModel(
            name='VendorExportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_company_reference', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('superseded', 'Superseded'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('delivery_method', models.CharField(help_text='api | sftp | email | webhook | manual', max_length=50)),
                ('schedule_cron', models.CharField(blank=True, help_text='Cron expression for automated windows. Blank = manual only.', max_length=100)),
                ('window_duration_minutes', models.PositiveIntegerField(default=60)),
                ('schedule_timezone', models.CharField(default='UTC', max_length=50)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supersedes', to='routing.vendorexportschedule')),
            ],
            options={
                'db_table': 'routing_vendor_export_schedule',
            },
        ),
        migrations.CreateModel(
            name='VendorExportWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_company_reference', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('open', 'Open'), ('processing', 'Processing'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='windows', to='routing.vendorexportschedule')),
            ],
            options={
                'db_table': 'routing_vendor_export_window',
            },
        ),
        migrations.CreateModel(
            name='VendorExportDeliveryEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_company_reference', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('attempted', 'Attempted'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('superseded', 'Superseded')], default='pending', max_length=20)),
                ('delivery_method', models.CharField(max_length=50)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='routing.vendorexportdeliveryattempt')),
                ('window', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_evidence', to='routing.vendorexportwindow')),
            ],
            options={
                'db_table': 'routing_vendor_export_delivery_evidence',
            },
        ),
        migrations.AddField(
            model_name='vendorexportdeliveryattempt',
            name='window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_attempts', to='routing.vendorexportwindow'),
        ),
        migrations.CreateModel(
            name='VendorExportBatchItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('included_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('routed_suborder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_items', to='routing.routedsuborder')),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_items', to='routing.vendorexportwindow')),
            ],
            options={
                'db_table': 'routing_vendor_export_batch_item',
            },
        ),
        migrations.AddIndex(
            model_name='routedsuborder',
            index=models.Index(fields=['vendor_company_reference', 'status'], name='routing_rou_vendor__03f45d_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorexportschedule',
            index=models.Index(fields=['vendor_company_reference', 'status'], name='routing_ven_vendor__593644_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorexportwindow',
            index=models.Index(fields=['vendor_company_reference', 'status', 'opens_at'], name='routing_ven_vendor__f0da8c_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorexportdeliveryevidence',
            index=models.Index(fields=['vendor_company_reference', 'status'], name='routing_ven_vendor__0bcac7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vendorexportbatchitem',
            unique_together={('window', 'routed_suborder')},
        ),
    ]
