# Generated by Django 5.0.6 on 2026-07-27 16:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_alter_order_status_alter_routedsuborder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorOrderExportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_company_reference', models.UUIDField(db_index=True)),
                ('buyer_company_reference', models.UUIDField(db_index=True)),
                ('filename', models.CharField(max_length=500)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_count', models.PositiveIntegerField()),
                ('suborder_count', models.PositiveIntegerField()),
                ('sending_method', models.CharField(default='email', max_length=50)),
                ('recipients', models.JSONField(default=list)),
                ('trigger_type', models.CharField(help_text='system | user', max_length=20)),
                ('status_before', models.CharField(default='placed', max_length=30)),
                ('status_after', models.CharField(default='processing', max_length=30)),
                ('csv_backup', models.TextField(help_text='Backup copy of the raw generated CSV content')),
                ('is_reexport', models.BooleanField(default=False)),
                ('audit_reference', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('original_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reexports', to='routing.vendororderexportlog')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_logs', to='routing.vendorexportwindow')),
            ],
            options={
                'db_table': 'routing_vendor_order_export_log',
                'indexes': [models.Index(fields=['vendor_company_reference', 'buyer_company_reference'], name='routing_ven_vendor__fada64_idx'), models.Index(fields=['sent_at'], name='routing_ven_sent_at_5febd7_idx')],
            },
        ),
    ]
