# Generated by Django 5.0.6 on 2026-07-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0004_vendororderexportlog_email_send_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('routed', 'Routed'), ('partially_routed', 'Partially Routed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('placed', 'Placed'), ('processing', 'Processing'), ('shipment_pending', 'Shipment Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='routedsuborder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('routed', 'Routed'), ('partially_routed', 'Partially Routed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('placed', 'Placed'), ('processing', 'Processing'), ('shipment_pending', 'Shipment Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=30),
        ),
    ]
