# Generated by Django 5.0.6 on 2026-07-30 10:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0005_alter_order_status_alter_routedsuborder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendororderexportlog',
            name='last_reexport_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vendororderexportlog',
            name='last_reexported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendororderexportlog',
            name='last_reexported_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendororderexportlog',
            name='reexport_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='VendorOrderReexportAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_id', models.CharField(blank=True, max_length=50)),
                ('attempt_number', models.PositiveIntegerField()),
                ('trigger_type', models.CharField(default='USER', max_length=20)),
                ('triggered_by_name', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='QUEUED', max_length=30)),
                ('recipient_email', models.CharField(blank=True, max_length=500)),
                ('cc_bcc', models.JSONField(blank=True, default=list)),
                ('delivery_method', models.CharField(default='email', max_length=50)),
                ('email_provider_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('attempt_started_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_completed_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_result', models.TextField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('file_checksum', models.CharField(blank=True, max_length=255)),
                ('file_storage_reference', models.CharField(blank=True, max_length=500)),
                ('parent_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reexport_attempts', to='routing.vendororderexportlog')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'routing_vendor_order_reexport_attempt',
                'ordering': ['attempt_number'],
            },
        ),
    ]
