# Generated by Django 5.0.6 on 2026-07-30 10:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0006_vendororderexportlog_last_reexport_status_and_more'),
        ('tenant', '0008_company_order_digest_emails_company_return_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendororderreexportattempt',
            old_name='attempt_completed_at',
            new_name='completed_at',
        ),
        migrations.RenameField(
            model_name='vendororderreexportattempt',
            old_name='status',
            new_name='delivery_status',
        ),
        migrations.RenameField(
            model_name='vendororderreexportattempt',
            old_name='attempt_started_at',
            new_name='processing_started_at',
        ),
        migrations.RenameField(
            model_name='vendororderreexportattempt',
            old_name='email_provider_message_id',
            new_name='provider_message_id',
        ),
        migrations.RenameField(
            model_name='vendororderreexportattempt',
            old_name='reason',
            new_name='reason_code',
        ),
        migrations.RenameField(
            model_name='vendororderreexportattempt',
            old_name='explanation',
            new_name='reason_notes',
        ),
        migrations.RenameField(
            model_name='vendororderreexportattempt',
            old_name='attempt_id',
            new_name='reexport_attempt_id',
        ),
        migrations.RenameField(
            model_name='vendororderreexportattempt',
            old_name='triggered_by_name',
            new_name='triggered_by_user_name_snapshot',
        ),
        migrations.RemoveField(
            model_name='vendororderreexportattempt',
            name='cc_bcc',
        ),
        migrations.RemoveField(
            model_name='vendororderreexportattempt',
            name='delivery_result',
        ),
        migrations.RemoveField(
            model_name='vendororderreexportattempt',
            name='parent_batch',
        ),
        migrations.RemoveField(
            model_name='vendororderreexportattempt',
            name='recipient_email',
        ),
        migrations.RemoveField(
            model_name='vendororderreexportattempt',
            name='retry_count',
        ),
        migrations.RemoveField(
            model_name='vendororderreexportattempt',
            name='triggered_by',
        ),
        migrations.AddField(
            model_name='vendororderreexportattempt',
            name='correlation_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='vendororderreexportattempt',
            name='delivery_destination_snapshot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendororderreexportattempt',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendororderreexportattempt',
            name='original_export_batch',
            field=models.ForeignKey(db_column='original_export_batch_id', default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='reexport_attempts', to='routing.vendororderexportlog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendororderreexportattempt',
            name='triggered_by_company',
            field=models.ForeignKey(blank=True, db_column='triggered_by_company_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.company'),
        ),
        migrations.AddField(
            model_name='vendororderreexportattempt',
            name='triggered_by_role_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendororderreexportattempt',
            name='triggered_by_user',
            field=models.ForeignKey(blank=True, db_column='triggered_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendororderreexportattempt',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
