# Generated by Django 5.0.6 on 2026-07-30 13:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0007_rename_attempt_completed_at_vendororderreexportattempt_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendororderexportlog',
            name='correlation_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='vendororderexportlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendororderexportlog',
            name='system_job_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendororderexportlog',
            name='system_process_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendororderexportlog',
            name='system_process_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendororderexportlog',
            name='system_schedule_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendororderexportlog',
            name='triggered_by_company_name_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendororderexportlog',
            name='triggered_by_role_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendororderexportlog',
            name='triggered_by_user_name_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendororderexportlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendororderreexportattempt',
            name='system_job_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendororderreexportattempt',
            name='system_process_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendororderreexportattempt',
            name='system_process_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendororderreexportattempt',
            name='system_schedule_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendororderreexportattempt',
            name='triggered_by_company_name_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
