# Generated by Django 5.0.6 on 2026-07-31 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0008_vendororderexportlog_correlation_id_and_more'),
        ('tenant', '0008_company_order_digest_emails_company_return_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendororderreexportattempt',
            old_name='triggered_by_company_name_snapshot',
            new_name='actor_company_name_snapshot',
        ),
        migrations.RenameField(
            model_name='vendororderreexportattempt',
            old_name='system_process_id',
            new_name='actor_process_code',
        ),
        migrations.RenameField(
            model_name='vendororderreexportattempt',
            old_name='system_process_name',
            new_name='actor_process_name',
        ),
        migrations.RenameField(
            model_name='vendororderreexportattempt',
            old_name='delivery_status',
            new_name='result_status',
        ),
        migrations.RemoveField(
            model_name='vendororderreexportattempt',
            name='triggered_by_company',
        ),
        migrations.RemoveField(
            model_name='vendororderreexportattempt',
            name='triggered_by_role_snapshot',
        ),
        migrations.RemoveField(
            model_name='vendororderreexportattempt',
            name='triggered_by_user',
        ),
        migrations.RemoveField(
            model_name='vendororderreexportattempt',
            name='triggered_by_user_name_snapshot',
        ),
        migrations.AddField(
            model_name='vendororderreexportattempt',
            name='action_type',
            field=models.CharField(choices=[('ORIGINAL_EXPORT', 'ORIGINAL_EXPORT'), ('REEXPORT', 'REEXPORT'), ('AUTOMATIC_RETRY', 'AUTOMATIC_RETRY'), ('MANUAL_RETRY', 'MANUAL_RETRY'), ('DOWNLOAD', 'DOWNLOAD')], default='REEXPORT', max_length=50),
        ),
        migrations.AddField(
            model_name='vendororderreexportattempt',
            name='actor_company',
            field=models.ForeignKey(blank=True, db_column='actor_company_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.company'),
        ),
        migrations.AddField(
            model_name='vendororderreexportattempt',
            name='actor_role_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendororderreexportattempt',
            name='actor_user',
            field=models.ForeignKey(blank=True, db_column='actor_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendororderreexportattempt',
            name='actor_user_name_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendororderreexportattempt',
            name='parent_attempt',
            field=models.ForeignKey(blank=True, db_column='parent_attempt_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_attempts', to='routing.vendororderreexportattempt'),
        ),
        migrations.AlterField(
            model_name='vendororderreexportattempt',
            name='reason_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
