# Generated by Django 5.0.6 on 2026-07-31 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0009_rename_triggered_by_company_name_snapshot_vendororderreexportattempt_actor_company_name_snapshot_and'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendororderexportlog',
            name='recipients',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
