# Generated by Django 5.0.6 on 2026-09-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0011_alter_order_status_alter_routedsuborder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, db_index=True, help_text='Standard Order ID starting with 1000 + company slug', max_length=100, null=True, unique=True),
        ),
    ]
