# Generated by Django 5.0.6 on 2026-06-01 13:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EffectivePriceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_reference', models.UUIDField(db_index=True)),
                ('channel', models.CharField(choices=[('online_dtc', 'Online / Direct-to-Consumer'), ('bulk_po', 'Bulk Purchase Order'), ('owned_channel', 'Owned Channel / Kaseory'), ('buyer_storefront', 'Buyer Storefront'), ('marketplace', 'Marketplace (placeholder)'), ('retail_pos', 'Retail POS (placeholder)'), ('promotional', 'Promotional Campaign (placeholder)'), ('buyer_contract', 'Buyer-Specific Contract (placeholder)')], db_index=True, max_length=30)),
                ('vendor_wholesale_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('vendor_side_commission_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('buyer_side_commission_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('buyer_facing_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('bindability_status', models.CharField(choices=[('order_bindable', 'Order Bindable'), ('procurement_bindable', 'Procurement Bindable'), ('invoice_bindable', 'Invoice Bindable'), ('export_bindable', 'Export Bindable'), ('not_bindable', 'Not Bindable'), ('requote_required', 'Requote Required'), ('expired', 'Expired'), ('superseded', 'Superseded')], max_length=30)),
                ('procurement_bindable', models.BooleanField(default=False)),
                ('invoice_bindable', models.BooleanField(default=False)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('snapshot_hash', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('superseded_by_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supersedes', to='pricing.effectivepricesnapshot')),
            ],
            options={
                'db_table': 'pricing_effective_price_snapshot',
            },
        ),
        migrations.CreateModel(
            name='POPricingBindability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_order_reference', models.UUIDField(db_index=True)),
                ('procurement_bindable_status', models.CharField(choices=[('order_bindable', 'Order Bindable'), ('procurement_bindable', 'Procurement Bindable'), ('invoice_bindable', 'Invoice Bindable'), ('export_bindable', 'Export Bindable'), ('not_bindable', 'Not Bindable'), ('requote_required', 'Requote Required'), ('expired', 'Expired'), ('superseded', 'Superseded')], max_length=30)),
                ('invoice_bindable_status', models.CharField(choices=[('order_bindable', 'Order Bindable'), ('procurement_bindable', 'Procurement Bindable'), ('invoice_bindable', 'Invoice Bindable'), ('export_bindable', 'Export Bindable'), ('not_bindable', 'Not Bindable'), ('requote_required', 'Requote Required'), ('expired', 'Expired'), ('superseded', 'Superseded')], max_length=30)),
                ('requote_required', models.BooleanField(default=False)),
                ('requote_reason', models.TextField(blank=True)),
                ('accepted_price_variance_reference', models.UUIDField(blank=True, null=True)),
                ('pricing_evidence_reference', models.UUIDField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.effectivepricesnapshot')),
            ],
            options={
                'db_table': 'pricing_po_bindability',
            },
        ),
        migrations.CreateModel(
            name='PricingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_company_reference', models.UUIDField(db_index=True)),
                ('buyer_company_reference', models.UUIDField(blank=True, db_index=True, help_text='Null = platform-default profile for this vendor', null=True)),
                ('channel', models.CharField(choices=[('online_dtc', 'Online / Direct-to-Consumer'), ('bulk_po', 'Bulk Purchase Order'), ('owned_channel', 'Owned Channel / Kaseory'), ('buyer_storefront', 'Buyer Storefront'), ('marketplace', 'Marketplace (placeholder)'), ('retail_pos', 'Retail POS (placeholder)'), ('promotional', 'Promotional Campaign (placeholder)'), ('buyer_contract', 'Buyer-Specific Contract (placeholder)')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('superseded', 'Superseded'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('vendor_side_commission_rate', models.DecimalField(blank=True, decimal_places=4, help_text='e.g. 0.0700 = 7%. Configurable default — not a hard-coded rule.', max_digits=6, null=True)),
                ('buyer_side_commission_rate', models.DecimalField(blank=True, decimal_places=4, help_text='e.g. 0.0700 = 7%. Configurable default — not a hard-coded rule.', max_digits=6, null=True)),
                ('markup_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('rounding_rule', models.CharField(default='round_half_up', max_length=30)),
                ('order_bindable', models.BooleanField(default=True)),
                ('procurement_bindable', models.BooleanField(default=False)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pricing_profile',
                'indexes': [models.Index(fields=['vendor_company_reference', 'channel', 'status'], name='pricing_pro_vendor__e5ecc7_idx')],
            },
        ),
        migrations.AddField(
            model_name='effectivepricesnapshot',
            name='pricing_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='pricing.pricingprofile'),
        ),
        migrations.CreateModel(
            name='ReturnAdjustmentPricingEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_reference', models.UUIDField(db_index=True)),
                ('adjustment_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('adjustment_currency', models.CharField(default='USD', max_length=3)),
                ('adjustment_reason', models.CharField(max_length=200)),
                ('line_disposition', models.CharField(blank=True, help_text='e.g. full_refund, partial_refund, restocking_fee, no_refund', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_adjustments', to='pricing.effectivepricesnapshot')),
            ],
            options={
                'db_table': 'pricing_return_adjustment_evidence',
            },
        ),
        migrations.CreateModel(
            name='BuyerFacingPricingVisibilityEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_reference', models.UUIDField(db_index=True)),
                ('company_scope_reference', models.UUIDField(db_index=True)),
                ('channel', models.CharField(choices=[('online_dtc', 'Online / Direct-to-Consumer'), ('bulk_po', 'Bulk Purchase Order'), ('owned_channel', 'Owned Channel / Kaseory'), ('buyer_storefront', 'Buyer Storefront'), ('marketplace', 'Marketplace (placeholder)'), ('retail_pos', 'Retail POS (placeholder)'), ('promotional', 'Promotional Campaign (placeholder)'), ('buyer_contract', 'Buyer-Specific Contract (placeholder)')], max_length=30)),
                ('tenant_scope_version', models.CharField(blank=True, max_length=100)),
                ('channel_eligibility_reference', models.UUIDField(blank=True, null=True)),
                ('product_channel_flag_version', models.CharField(blank=True, max_length=100)),
                ('redaction_decision', models.CharField(default='allowed', help_text='allowed | redacted | blocked', max_length=30)),
                ('recheck_before_display', models.BooleanField(default=False)),
                ('visibility_granted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.effectivepricesnapshot')),
            ],
            options={
                'db_table': 'pricing_visibility_evidence',
                'indexes': [models.Index(fields=['buyer_reference', 'channel', 'visibility_granted'], name='pricing_vis_buyer_r_bf7015_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='effectivepricesnapshot',
            index=models.Index(fields=['product_reference', 'channel', 'is_current'], name='pricing_eff_product_43099e_idx'),
        ),
        migrations.AddIndex(
            model_name='effectivepricesnapshot',
            index=models.Index(fields=['bindability_status'], name='pricing_eff_bindabi_f29a02_idx'),
        ),
    ]
