# Generated by Django 5.0.6 on 2026-06-18 17:14

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCommissionAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_company_reference', models.UUIDField(db_index=True, help_text='Tenant Company vendor ID')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('terminated', 'Terminated')], default='draft', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.UUIDField(blank=True, help_text='User ID of the CIXCI admin who approved the agreement', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pricing_vendor_commission_agreement',
            },
        ),
        migrations.AddField(
            model_name='effectivepricesnapshot',
            name='buyer_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=14.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='effectivepricesnapshot',
            name='buyer_pricing_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='effectivepricesnapshot',
            name='vendor_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
