# Generated by Django 5.0.6 on 2026-06-19 15:21

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_vendorcommissionagreement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_company_reference', models.UUIDField(db_index=True, help_text='Tenant Company vendor ID')),
                ('product_reference', models.UUIDField(blank=True, db_index=True, help_text='Optional catalog product reference', null=True)),
                ('sku', models.CharField(db_index=True, max_length=255)),
                ('buyer_company_reference', models.UUIDField(blank=True, db_index=True, help_text='Optional buyer company reference (null = applies to all)', null=True)),
                ('approved_minimum_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('approval_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pricing_map_exception',
                'indexes': [models.Index(fields=['vendor_company_reference', 'sku', 'status'], name='pricing_map_vendor__59ab18_idx'), models.Index(fields=['buyer_company_reference', 'status'], name='pricing_map_buyer_c_601944_idx')],
            },
        ),
    ]
