# Generated by Django 5.0.6 on 2026-06-01 13:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDateEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shipment_line_reference', models.UUIDField(db_index=True)),
                ('vendor_reported_delivery_date', models.DateField()),
                ('validation_outcome', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('review_required', 'Review Required'), ('pending', 'Pending Validation')], default='pending', max_length=20)),
                ('validation_detail', models.JSONField(default=dict)),
                ('triggers_delivered_state', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'fulfillment_delivery_date_evidence',
            },
        ),
        migrations.CreateModel(
            name='BuyerUpdateReadySignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_reference', models.UUIDField(db_index=True)),
                ('buyer_reference', models.UUIDField(db_index=True)),
                ('company_scope_reference', models.UUIDField(db_index=True)),
                ('update_kind', models.CharField(choices=[('shipment', 'Shipment Update'), ('delivery', 'Delivery Update'), ('correction', 'Delivery Date Correction')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('held', 'Held (awaiting all vendors)'), ('eligible', 'Eligible'), ('dispatched', 'Dispatched'), ('acknowledged', 'Acknowledged'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('expected_vendor_count', models.PositiveSmallIntegerField(default=1)),
                ('confirmed_vendor_count', models.PositiveSmallIntegerField(default=0)),
                ('all_vendors_confirmed', models.BooleanField(default=False)),
                ('buyer_integration_profile_reference', models.UUIDField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'fulfillment_buyer_update_signal',
                'indexes': [models.Index(fields=['order_reference', 'update_kind', 'status'], name='fulfillment_order_r_c37eaa_idx'), models.Index(fields=['buyer_reference', 'status'], name='fulfillment_buyer_r_8198f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryDateCorrectionEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('corrected_delivery_date', models.DateField()),
                ('correction_reason', models.TextField()),
                ('authority_reference', models.UUIDField(help_text='Actor with correction authority')),
                ('audit_record_reference', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_delivery_date_evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='fulfillment.deliverydateevidence')),
            ],
            options={
                'db_table': 'fulfillment_delivery_date_correction',
            },
        ),
        migrations.CreateModel(
            name='FulfillmentHandoff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('routed_suborder_reference', models.UUIDField(db_index=True, unique=True)),
                ('vendor_company_reference', models.UUIDField(db_index=True)),
                ('company_scope_reference', models.UUIDField(db_index=True)),
                ('status', models.CharField(default='received', help_text='received | processing | shipped | delivered | exception | closed', max_length=50)),
                ('delivery_evidence_reference', models.UUIDField(blank=True, help_text='VendorExportDeliveryEvidence ID (read-only reference from Order Routing)', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fulfillment_handoff',
                'indexes': [models.Index(fields=['vendor_company_reference', 'status'], name='fulfillment_vendor__be2055_idx')],
            },
        ),
        migrations.AddField(
            model_name='deliverydateevidence',
            name='handoff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_date_evidence', to='fulfillment.fulfillmenthandoff'),
        ),
        migrations.CreateModel(
            name='SLAEvaluationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_evidence_reference', models.UUIDField(help_text='VendorExportDeliveryEvidence ID')),
                ('delivery_confirmed_at', models.UUIDField(blank=True, help_text='Snapshot of confirmed_at from delivery evidence at evaluation time', null=True)),
                ('expected_response_by', models.DateTimeField()),
                ('fulfillment_import_received_timestamp', models.DateTimeField(blank=True, help_text='PR #92: Transport receipt timestamp. NOT post-validation acceptance.', null=True)),
                ('outcome', models.CharField(choices=[('on_time', 'On Time'), ('late', 'Late'), ('missing', 'Missing'), ('partial', 'Partial'), ('pending', 'Pending (evaluation in progress)'), ('overridden', 'Overridden / Excused')], default='pending', max_length=20)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('handoff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sla_evaluations', to='fulfillment.fulfillmenthandoff')),
            ],
            options={
                'db_table': 'fulfillment_sla_evaluation',
            },
        ),
        migrations.CreateModel(
            name='PartialFulfillmentResponseException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('overridden', 'Overridden / Excused'), ('closed', 'Closed')], default='open', max_length=20)),
                ('expected_line_count', models.PositiveIntegerField()),
                ('received_line_count', models.PositiveIntegerField()),
                ('missing_line_references', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sla_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fulfillment.slaevaluationrecord')),
            ],
            options={
                'db_table': 'fulfillment_partial_response_exception',
            },
        ),
        migrations.CreateModel(
            name='MissingFulfillmentImportException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('overridden', 'Overridden / Excused'), ('closed', 'Closed')], default='open', max_length=20)),
                ('late_arrival_reference', models.UUIDField(blank=True, help_text='LateFulfillmentImportException ID created when import arrives. Never mutate Missing into Late.', null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sla_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fulfillment.slaevaluationrecord')),
            ],
            options={
                'db_table': 'fulfillment_missing_import_exception',
            },
        ),
        migrations.CreateModel(
            name='LateFulfillmentImportException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('overridden', 'Overridden / Excused'), ('closed', 'Closed')], default='open', max_length=20)),
                ('actual_import_received_at', models.DateTimeField()),
                ('delay_hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sla_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fulfillment.slaevaluationrecord')),
            ],
            options={
                'db_table': 'fulfillment_late_import_exception',
            },
        ),
        migrations.CreateModel(
            name='SLAOverrideExcuseEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exception_type', models.CharField(help_text='late | missing | partial', max_length=50)),
                ('exception_reference', models.UUIDField()),
                ('override_reason', models.TextField()),
                ('override_category', models.CharField(help_text='e.g. weather_event, system_outage, mutual_agreement, admin_error', max_length=100)),
                ('actor_reference', models.UUIDField()),
                ('audit_record_reference', models.UUIDField(blank=True, null=True)),
                ('reversal_reference', models.UUIDField(blank=True, null=True)),
                ('is_reversal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sla_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fulfillment.slaevaluationrecord')),
            ],
            options={
                'db_table': 'fulfillment_sla_override_evidence',
            },
        ),
        migrations.CreateModel(
            name='VendorFulfillmentResponseSLAPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_company_reference', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('superseded', 'Superseded'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('response_window_hours', models.PositiveIntegerField(help_text='Hours from confirmed delivery to expected fulfillment import')),
                ('partial_threshold_percent', models.DecimalField(decimal_places=2, default=100.0, help_text='Percent of ordered items required to be non-partial', max_digits=5)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supersedes', to='fulfillment.vendorfulfillmentresponseslapolicy')),
            ],
            options={
                'db_table': 'fulfillment_sla_policy',
            },
        ),
        migrations.AddField(
            model_name='slaevaluationrecord',
            name='sla_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fulfillment.vendorfulfillmentresponseslapolicy'),
        ),
        migrations.AddIndex(
            model_name='deliverydateevidence',
            index=models.Index(fields=['shipment_line_reference'], name='fulfillment_shipmen_e8ab1f_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorfulfillmentresponseslapolicy',
            index=models.Index(fields=['vendor_company_reference', 'status'], name='fulfillment_vendor__42484a_idx'),
        ),
    ]
