# Generated by Django 5.0.6 on 2026-07-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillmenthandoff',
            name='delivered_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fulfillmenthandoff',
            name='shipped_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fulfillmenthandoff',
            name='shipping_carrier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fulfillmenthandoff',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fulfillmenthandoff',
            name='vendor_order_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
