# Generated by Django 5.0.6 on 2026-07-28 08:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0002_fulfillmenthandoff_delivered_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfillmenthandoff',
            name='status',
            field=models.CharField(default='received', help_text='received | processing | shipped | delivered | exception | closed | tracking_missing | tracking_invalid | review_required | delivery_exception', max_length=50),
        ),
        migrations.CreateModel(
            name='VendorShippingImportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_company_reference', models.UUIDField(db_index=True)),
                ('company_scope_reference', models.UUIDField(db_index=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('csv_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('csv_content', models.TextField(help_text='Full text of the uploaded CSV file')),
                ('rows_applied', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0)),
                ('rows_rejected', models.PositiveIntegerField(default=0)),
                ('rows_review_required', models.PositiveIntegerField(default=0)),
                ('results_payload', models.JSONField(default=dict, help_text='Detailed row-by-row outcomes and validation errors')),
                ('audit_reference', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fulfillment_vendor_shipping_import_log',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
