# Generated by Django 5.0.6 on 2026-07-28 10:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0003_alter_fulfillmenthandoff_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ran', models.CharField(db_index=True, max_length=255, unique=True)),
                ('suborder_reference', models.UUIDField(db_index=True)),
                ('buyer_reference', models.UUIDField(db_index=True)),
                ('reason', models.TextField(blank=True)),
                ('return_initiation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_quantity', models.PositiveIntegerField(default=1)),
                ('vendor_wholesale_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('pricing_snapshot_reference', models.UUIDField(blank=True, null=True)),
                ('sku', models.CharField(max_length=100)),
                ('upc', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('return_sent_to_vendor', 'Return Sent to Vendor'), ('return_received', 'Return Received'), ('return_refunded', 'Return Refunded'), ('return_rejected', 'Return Rejected')], default='return_sent_to_vendor', max_length=50)),
                ('return_received_date', models.DateTimeField(blank=True, null=True)),
                ('return_refunded_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('rejected_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fulfillment_return_request',
                'indexes': [models.Index(fields=['suborder_reference'], name='fulfillment_suborde_d7b7d0_idx'), models.Index(fields=['buyer_reference'], name='fulfillment_buyer_r_69b0e1_idx'), models.Index(fields=['status'], name='fulfillment_status_5a4587_idx')],
            },
        ),
        migrations.CreateModel(
            name='VendorReturnImportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_company_reference', models.UUIDField(db_index=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('csv_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('csv_content', models.TextField(help_text='Full text of the uploaded CSV file')),
                ('rows_applied', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0)),
                ('rows_rejected', models.PositiveIntegerField(default=0)),
                ('results_payload', models.JSONField(default=dict, help_text='Detailed row-by-row outcomes and validation errors')),
                ('audit_reference', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fulfillment_vendor_return_import_log',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
