# Generated by Django 5.0.6 on 2026-07-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0004_returnrequest_vendorreturnimportlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorreturnimportlog',
            name='company_scope_reference',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorreturnimportlog',
            name='return_export_batch_reference',
            field=models.UUIDField(blank=True, help_text='Reference to original return export batch', null=True),
        ),
        migrations.AddField(
            model_name='vendorreturnimportlog',
            name='rows_review_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('return_sent_to_vendor', 'Return Sent to Vendor'), ('return_received', 'Return Received'), ('return_refunded', 'Return Refunded'), ('return_rejected', 'Return Rejected'), ('return_closed', 'Return Closed')], default='return_sent_to_vendor', max_length=50),
        ),
    ]
