# Generated by Django 5.0.6 on 2026-09-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0006_add_missing_handoff_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='item_condition',
            field=models.CharField(blank=True, choices=[('unopened', 'Unopened'), ('like_new', 'Like New'), ('used', 'Used'), ('damaged', 'Damaged'), ('defective', 'Defective'), ('other', 'Other')], help_text='Physical condition of the item when returned', max_length=100),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='refund_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processed', 'Processed'), ('rejected', 'Rejected'), ('partial', 'Partial')], help_text='Current status of the refund processing', max_length=50),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='restocking_fee',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Fee deducted from refund for restocking the returned item', max_digits=12, null=True),
        ),
    ]
