# Generated by Django 5.0.6 on 2026-06-01 08:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_code', models.CharField(db_index=True, max_length=200)),
                ('event_description', models.TextField(blank=True)),
                ('status', models.CharField(max_length=50)),
                ('actor_reference', models.UUIDField(blank=True, help_text='Human user ID', null=True)),
                ('service_trigger_reference', models.CharField(blank=True, help_text='Non-human service identity (scheduler, webhook handler, celery task)', max_length=200)),
                ('company_scope_reference', models.UUIDField(help_text='Tenant Company scope — REQUIRED')),
                ('source_module', models.CharField(blank=True, max_length=100)),
                ('source_record_type', models.CharField(blank=True, max_length=150)),
                ('source_record_id', models.UUIDField(blank=True, null=True)),
                ('evidence_record_reference', models.UUIDField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('retention_class', models.CharField(choices=[('transient', 'Transient'), ('standard', 'Standard'), ('extended', 'Extended'), ('regulatory', 'Regulatory'), ('legal_hold', 'Legal Hold'), ('audit_critical', 'Audit Critical')], default='standard', max_length=30)),
                ('redaction_class', models.CharField(choices=[('public_metadata_placeholder', 'Public Metadata'), ('buyer_visible_audit', 'Buyer Visible Audit'), ('vendor_visible_audit', 'Vendor Visible Audit'), ('internal_operations', 'Internal Operations'), ('customer_sensitive_restricted', 'Customer Sensitive Restricted'), ('pricing_sensitive_restricted', 'Pricing Sensitive Restricted'), ('invoice_sensitive_restricted', 'Invoice Sensitive Restricted'), ('warranty_sensitive_restricted', 'Warranty Sensitive Restricted'), ('tenant_security_restricted', 'Tenant Security Restricted'), ('audit_only', 'Audit Only')], default='internal_operations', max_length=50)),
                ('access_class', models.CharField(choices=[('public_metadata', 'Public Metadata'), ('buyer_visible', 'Buyer Visible'), ('vendor_visible', 'Vendor Visible'), ('internal_operations', 'Internal Operations'), ('system_admin_only', 'System Admin Only'), ('compliance_only', 'Compliance Only')], default='internal_operations', max_length=30)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'audit_record',
                'indexes': [models.Index(fields=['source_module', 'source_record_id'], name='audit_recor_source__d1338d_idx'), models.Index(fields=['company_scope_reference', 'created_at'], name='audit_recor_company_8ac3b1_idx'), models.Index(fields=['event_code', 'created_at'], name='audit_recor_event_c_ab7f18_idx')],
            },
        ),
        migrations.CreateModel(
            name='EvidenceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(db_index=True, help_text='e.g. file_evidence, api_transmission_evidence, import_evidence, summary_evidence', max_length=100)),
                ('evidence_status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('amended', 'Amended')], default='active', max_length=20)),
                ('source_module', models.CharField(blank=True, max_length=100)),
                ('source_record_type', models.CharField(blank=True, max_length=150)),
                ('source_record_id', models.UUIDField(blank=True, null=True)),
                ('source_snapshot_reference', models.UUIDField(blank=True, help_text='Minimized snapshot — per Source Snapshot Minimization Rule', null=True)),
                ('company_scope_reference', models.UUIDField(db_index=True)),
                ('actor_reference', models.UUIDField(blank=True, null=True)),
                ('service_trigger_reference', models.CharField(blank=True, max_length=200)),
                ('evidence_attachment_reference', models.UUIDField(blank=True, null=True)),
                ('evidence_hash_reference', models.CharField(blank=True, help_text='Hash of evidence payload at creation (algorithm is implementation-level)', max_length=512)),
                ('evidence_schema_version', models.CharField(default='1.0', max_length=20)),
                ('source_event_reference', models.CharField(blank=True, max_length=255)),
                ('correlation_reference', models.UUIDField(blank=True, null=True)),
                ('trace_reference', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('replay_safe_dedupe_reference', models.CharField(blank=True, max_length=255)),
                ('retention_class', models.CharField(choices=[('transient', 'Transient'), ('standard', 'Standard'), ('extended', 'Extended'), ('regulatory', 'Regulatory'), ('legal_hold', 'Legal Hold'), ('audit_critical', 'Audit Critical')], default='standard', max_length=30)),
                ('redaction_class', models.CharField(choices=[('public_metadata_placeholder', 'Public Metadata'), ('buyer_visible_audit', 'Buyer Visible Audit'), ('vendor_visible_audit', 'Vendor Visible Audit'), ('internal_operations', 'Internal Operations'), ('customer_sensitive_restricted', 'Customer Sensitive Restricted'), ('pricing_sensitive_restricted', 'Pricing Sensitive Restricted'), ('invoice_sensitive_restricted', 'Invoice Sensitive Restricted'), ('warranty_sensitive_restricted', 'Warranty Sensitive Restricted'), ('tenant_security_restricted', 'Tenant Security Restricted'), ('audit_only', 'Audit Only')], default='internal_operations', max_length=50)),
                ('access_class', models.CharField(choices=[('public_metadata', 'Public Metadata'), ('buyer_visible', 'Buyer Visible'), ('vendor_visible', 'Vendor Visible'), ('internal_operations', 'Internal Operations'), ('system_admin_only', 'System Admin Only'), ('compliance_only', 'Compliance Only')], default='internal_operations', max_length=30)),
                ('restricted_evidence', models.BooleanField(default=False)),
                ('raw_evidence_reference', models.UUIDField(blank=True, null=True)),
                ('redacted_view_reference', models.UUIDField(blank=True, null=True)),
                ('legal_hold_reference', models.UUIDField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('audit_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_records', to='audit.auditrecord')),
            ],
            options={
                'db_table': 'audit_evidence_record',
            },
        ),
        migrations.CreateModel(
            name='EvidenceAmendmentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_reference', models.UUIDField(help_text='Who submitted this amendment')),
                ('reason', models.TextField()),
                ('amendment_detail', models.JSONField(help_text='What was corrected — field name, old value, new value')),
                ('audit_record_reference', models.UUIDField(help_text='AuditRecord for this amendment action')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('evidence_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='audit.evidencerecord')),
            ],
            options={
                'db_table': 'audit_evidence_amendment',
            },
        ),
        migrations.CreateModel(
            name='EvidenceSupersessionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_module_correction_reference', models.UUIDField(help_text='Reference to the source-module correction that triggered this supersession')),
                ('actor_reference', models.UUIDField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('new_evidence_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supersedes', to='audit.evidencerecord')),
                ('prior_evidence_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='audit.evidencerecord')),
            ],
            options={
                'db_table': 'audit_evidence_supersession',
            },
        ),
        migrations.CreateModel(
            name='FileTrackingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_direction', models.CharField(choices=[('uploaded', 'Uploaded (external → CIXCI)'), ('generated', 'Generated (CIXCI-created)'), ('downloaded', 'Downloaded (CIXCI → external)')], max_length=20)),
                ('file_purpose', models.CharField(choices=[('product_import', 'Product Import'), ('product_export', 'Product Export'), ('vendor_order_export', 'Vendor Order Export'), ('vendor_return_export', 'Vendor Return Export'), ('vendor_shipping_import', 'Vendor Shipping Import'), ('vendor_delivery_import', 'Vendor Delivery Import'), ('vendor_return_import', 'Vendor Return Import'), ('media_upload', 'Media Upload'), ('invoice_export', 'Invoice Export'), ('report_export', 'Report Export'), ('audit_export', 'Audit Export'), ('unknown_other', 'Unknown / Other')], max_length=50)),
                ('file_lifecycle_status', models.CharField(choices=[('received', 'Received'), ('generated', 'Generated'), ('stored', 'Stored'), ('queued_for_validation', 'Queued for Validation'), ('validating', 'Validating'), ('validation_failed', 'Validation Failed'), ('validation_passed', 'Validation Passed'), ('processing', 'Processing'), ('processing_failed', 'Processing Failed'), ('processed', 'Processed'), ('partially_processed', 'Partially Processed'), ('duplicate_detected', 'Duplicate Detected'), ('superseded', 'Superseded'), ('replaced', 'Replaced'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('archived', 'Archived')], max_length=40)),
                ('file_name', models.CharField(max_length=500)),
                ('file_type', models.CharField(max_length=50)),
                ('file_version', models.CharField(blank=True, max_length=50)),
                ('file_storage_reference', models.CharField(blank=True, max_length=1000)),
                ('file_hash_reference', models.CharField(blank=True, max_length=512)),
                ('file_integrity_reference', models.UUIDField(blank=True, null=True)),
                ('source_module', models.CharField(max_length=100)),
                ('company_scope_reference', models.UUIDField(db_index=True)),
                ('vendor_reference', models.UUIDField(blank=True, null=True)),
                ('buyer_entity_scope', models.UUIDField(blank=True, null=True)),
                ('actor_reference', models.UUIDField(blank=True, null=True)),
                ('service_trigger_reference', models.CharField(blank=True, max_length=200)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('accepted_row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('failed_row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('validation_status', models.CharField(blank=True, max_length=50)),
                ('processing_status', models.CharField(blank=True, max_length=50)),
                ('error_summary', models.TextField(blank=True)),
                ('duplicate_file_detection_reference', models.UUIDField(blank=True, null=True)),
                ('correction_reupload_history_reference', models.UUIDField(blank=True, null=True)),
                ('masked_payload_reference', models.UUIDField(blank=True, null=True)),
                ('retention_class', models.CharField(choices=[('transient', 'Transient'), ('standard', 'Standard'), ('extended', 'Extended'), ('regulatory', 'Regulatory'), ('legal_hold', 'Legal Hold'), ('audit_critical', 'Audit Critical')], default='standard', max_length=30)),
                ('redaction_class', models.CharField(choices=[('public_metadata_placeholder', 'Public Metadata'), ('buyer_visible_audit', 'Buyer Visible Audit'), ('vendor_visible_audit', 'Vendor Visible Audit'), ('internal_operations', 'Internal Operations'), ('customer_sensitive_restricted', 'Customer Sensitive Restricted'), ('pricing_sensitive_restricted', 'Pricing Sensitive Restricted'), ('invoice_sensitive_restricted', 'Invoice Sensitive Restricted'), ('warranty_sensitive_restricted', 'Warranty Sensitive Restricted'), ('tenant_security_restricted', 'Tenant Security Restricted'), ('audit_only', 'Audit Only')], default='internal_operations', max_length=50)),
                ('access_class', models.CharField(choices=[('public_metadata', 'Public Metadata'), ('buyer_visible', 'Buyer Visible'), ('vendor_visible', 'Vendor Visible'), ('internal_operations', 'Internal Operations'), ('system_admin_only', 'System Admin Only'), ('compliance_only', 'Compliance Only')], default='internal_operations', max_length=30)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('audit_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_tracking_records', to='audit.auditrecord')),
                ('evidence_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_tracking_records', to='audit.evidencerecord')),
            ],
            options={
                'db_table': 'audit_file_tracking_record',
            },
        ),
        migrations.AddIndex(
            model_name='evidencerecord',
            index=models.Index(fields=['evidence_type', 'captured_at'], name='audit_evide_evidenc_305ce4_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencerecord',
            index=models.Index(fields=['source_module', 'source_record_id'], name='audit_evide_source__58f953_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencerecord',
            index=models.Index(fields=['company_scope_reference', 'captured_at'], name='audit_evide_company_068333_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencerecord',
            index=models.Index(fields=['evidence_status'], name='audit_evide_evidenc_725b42_idx'),
        ),
        migrations.AddIndex(
            model_name='filetrackingrecord',
            index=models.Index(fields=['company_scope_reference', 'file_purpose', 'created_at'], name='audit_file__company_7452b1_idx'),
        ),
        migrations.AddIndex(
            model_name='filetrackingrecord',
            index=models.Index(fields=['source_module', 'file_lifecycle_status'], name='audit_file__source__a500fb_idx'),
        ),
    ]
