# Generated by Django 5.0.6 on 2026-06-01 08:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('module', models.CharField(help_text='Owning module (e.g. catalog, devices, pricing)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Capability',
                'verbose_name_plural': 'Capabilities',
                'db_table': 'tenant_capability',
                'ordering': ['module', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('company_type', models.CharField(choices=[('cixci_internal', 'CIXCI Internal'), ('buyer', 'Buyer'), ('vendor', 'Vendor (Accessory)'), ('manufacturer', 'Device Manufacturer')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('external_id', models.CharField(blank=True, help_text='External system ID reference', max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('region_code', models.CharField(blank=True, max_length=50)),
                ('allowed_channels', models.JSONField(default=list, help_text='List of ChannelType values this company can access')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='Actor reference', null=True)),
                ('parent_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_companies', to='tenant.company')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'tenant_company',
            },
        ),
        migrations.CreateModel(
            name='CompanyEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('allowed_channels_override', models.JSONField(blank=True, help_text='If set, overrides company-level channel eligibility for this entity', null=True)),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('region_code', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entities', to='tenant.company')),
            ],
            options={
                'verbose_name': 'Company Entity',
                'verbose_name_plural': 'Company Entities',
                'db_table': 'tenant_company_entity',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_cixci_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('capabilities', models.ManyToManyField(blank=True, related_name='users', to='tenant.capability')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='tenant.companyentity')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'tenant_user',
            },
        ),
        migrations.CreateModel(
            name='CompanyRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='pending', max_length=20)),
                ('eligible_product_types', models.JSONField(default=list)),
                ('eligible_regions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_relationships', to=settings.AUTH_USER_MODEL)),
                ('buyer_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyer_relationships', to='tenant.company')),
                ('vendor_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_relationships', to='tenant.company')),
            ],
            options={
                'db_table': 'tenant_company_relationship',
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['company_type', 'status'], name='tenant_comp_company_5a8853_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['parent_company'], name='tenant_comp_parent__ea0b6a_idx'),
        ),
        migrations.AddIndex(
            model_name='companyentity',
            index=models.Index(fields=['company', 'status'], name='tenant_comp_company_b8dc18_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['entity', 'is_active'], name='tenant_user_entity__754571_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_cixci_admin'], name='tenant_user_is_cixc_ef0af1_idx'),
        ),
        migrations.AddIndex(
            model_name='companyrelationship',
            index=models.Index(fields=['buyer_company', 'status'], name='tenant_comp_buyer_c_bb7790_idx'),
        ),
        migrations.AddIndex(
            model_name='companyrelationship',
            index=models.Index(fields=['vendor_company', 'status'], name='tenant_comp_vendor__e75f8e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companyrelationship',
            unique_together={('buyer_company', 'vendor_company')},
        ),
    ]
