# Generated by Django 5.0.6 on 2026-06-10 12:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='approved_regions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='company',
            name='business_email_domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='capabilities',
            field=models.ManyToManyField(blank=True, related_name='companies', to='tenant.capability'),
        ),
        migrations.AddField(
            model_name='company',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_contact_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('cixci_internal', 'CIXCI Internal'), ('buyer', 'Buyer'), ('vendor', 'Vendor (Accessory)'), ('manufacturer', 'Device Manufacturer'), ('partner', 'Partner')], max_length=30),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_setup', 'Pending Setup'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived'), ('retired', 'Retired')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='ChildOnboardingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('brand_name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('region', models.CharField(max_length=50)),
                ('primary_contact', models.CharField(max_length=255)),
                ('business_email_domain', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='submitted', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision_timestamp', models.DateTimeField(blank=True, null=True)),
                ('decision_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_onboarding_requests', to=settings.AUTH_USER_MODEL)),
                ('parent_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_onboarding_requests', to='tenant.company')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_onboarding_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant_child_onboarding_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
