# Generated by Django 5.0.6 on 2026-06-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_company_address_company_approved_regions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='allowed_channels',
            field=models.JSONField(blank=True, default=list, help_text='List of ChannelType values this company can access'),
        ),
    ]
