# Generated by Django 5.0.6 on 2026-06-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_remove_company_address_company_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('cixci_internal', 'CIXCI Internal'), ('buyer', 'Buyer'), ('vendor', 'Vendor (Accessory)'), ('manufacturer', 'Device Manufacturer'), ('partner', 'Partner'), ('device_distributor', 'Device Distributor')], max_length=30),
        ),
    ]
