# Generated by Django 5.0.6 on 2026-06-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_alter_company_company_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='childonboardingrequest',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=14.0, help_text='Requested/assigned buyer-side commission rate in percent', max_digits=5),
        ),
        migrations.AddField(
            model_name='company',
            name='buyer_pricing_mode',
            field=models.CharField(choices=[('standard', 'Standard Buyer Commission'), ('no_commission', 'No Buyer Commission'), ('custom', 'Custom Buyer Commission')], default='standard', help_text='Determines how buyer-side commission is calculated', max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=14.0, help_text='Custom or standard commission rate in percent', max_digits=5),
        ),
    ]
