# Generated by Django 5.0.6 on 2026-06-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_childonboardingrequest_commission_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='map_pricing_enforced',
            field=models.BooleanField(default=False),
        ),
    ]
