# Generated by Django 5.0.6 on 2026-06-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0007_company_map_pricing_enforced'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='order_digest_emails',
            field=models.JSONField(blank=True, default=list, help_text='List of email addresses for automated order digests'),
        ),
        migrations.AddField(
            model_name='company',
            name='return_address',
            field=models.TextField(blank=True, help_text='Return Address for items'),
        ),
    ]
