# Generated by Django 5.0.6 on 2026-08-15 12:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0008_company_order_digest_emails_company_return_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapabilityDelegationEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='grant | revoke', max_length=20)),
                ('passed_7point_rule', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegation_actions', to=settings.AUTH_USER_MODEL)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenant.capability')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenant.company')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_delegations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant_capability_delegation_evidence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EffectiveCompanyAdminEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active_admin_count', models.PositiveIntegerField()),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_continuity_evidence', to='tenant.company')),
            ],
            options={
                'db_table': 'tenant_effective_admin_evidence',
                'ordering': ['-verified_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyUserMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('deactivated', 'Deactivated')], default='active', max_length=20)),
                ('role_bundle', models.CharField(default='standard_user', max_length=100)),
                ('is_company_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_capabilities', models.ManyToManyField(blank=True, related_name='membership_assignments', to='tenant.capability')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenant.company')),
                ('delegated_capabilities', models.ManyToManyField(blank=True, related_name='membership_delegations', to='tenant.capability')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenant.companyentity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant_company_user_membership',
                'indexes': [models.Index(fields=['company', 'status'], name='tenant_comp_company_05800d_idx'), models.Index(fields=['user', 'status'], name='tenant_comp_user_id_e51d83_idx')],
                'unique_together': {('user', 'company')},
            },
        ),
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('role_bundle', models.CharField(default='standard_user', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_capabilities', models.ManyToManyField(blank=True, related_name='invitations', to='tenant.capability')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('target_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_invitations', to='tenant.company')),
                ('target_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_invitations', to='tenant.companyentity')),
            ],
            options={
                'db_table': 'tenant_user_invitation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_company', 'status'], name='tenant_user_target__a8ffdf_idx'), models.Index(fields=['email', 'status'], name='tenant_user_email_e46fa6_idx')],
            },
        ),
    ]
