# Generated by Django 5.0.6 on 2026-09-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0009_capabilitydelegationevidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='return_address_line1',
            field=models.CharField(blank=True, help_text='Primary return address line', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='return_address_line2',
            field=models.CharField(blank=True, help_text='Secondary return address line', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='return_city',
            field=models.CharField(blank=True, help_text='Return address city', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='return_state',
            field=models.CharField(blank=True, help_text='Return address state', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='return_zip_code',
            field=models.CharField(blank=True, help_text='Return address zip/postal code', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='return_address',
            field=models.TextField(blank=True, help_text='Return Address for items (legacy single field)'),
        ),
    ]
