# Generated by Django 5.0.6 on 2026-06-01 13:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProductExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_reference', models.UUIDField(db_index=True)),
                ('company_scope_reference', models.UUIDField(db_index=True)),
                ('buyer_entity_reference', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('portfolio_snapshot_reference', models.UUIDField(blank=True, help_text='BuyerDevicePortfolioSnapshot ID used as basis for this export', null=True)),
                ('compatibility_projection_reference', models.UUIDField(blank=True, null=True)),
                ('include_incompatible', models.BooleanField(default=False)),
                ('format', models.CharField(default='csv', help_text='csv | json | xlsx', max_length=20)),
                ('output_file_reference', models.UUIDField(blank=True, null=True)),
                ('product_count', models.PositiveIntegerField(blank=True, null=True)),
                ('requested_by', models.UUIDField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'catalog_buyer_export_job',
                'indexes': [models.Index(fields=['buyer_reference', 'status', 'created_at'], name='catalog_buy_buyer_r_ff5a46_idx')],
            },
        ),
        migrations.CreateModel(
            name='BuyerProductExportSelectionSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_ids', models.JSONField(help_text='Frozen list of Product IDs at export time')),
                ('portfolio_snapshot_reference', models.UUIDField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('export_job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='selection_snapshot', to='catalog.buyerproductexportjob')),
            ],
            options={
                'db_table': 'catalog_export_selection_snapshot',
            },
        ),
        migrations.CreateModel(
            name='BuyerScopedCompatibilityProjection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_reference', models.UUIDField(db_index=True)),
                ('company_scope_reference', models.UUIDField(db_index=True)),
                ('buyer_entity_reference', models.UUIDField(db_index=True)),
                ('portfolio_snapshot_reference', models.UUIDField(help_text='BuyerDevicePortfolioSnapshot ID from Device Catalog (read-only reference)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('stale', 'Stale'), ('recalculating', 'Recalculating'), ('review_required', 'Review Required'), ('empty_portfolio', 'Empty Portfolio')], default='recalculating', max_length=20)),
                ('compatible_product_ids', models.JSONField(default=list)),
                ('compatible_product_count', models.PositiveIntegerField(default=0)),
                ('incompatible_product_ids', models.JSONField(default=list)),
                ('last_recalculated_at', models.DateTimeField(blank=True, null=True)),
                ('recalculation_trigger', models.CharField(blank=True, help_text='e.g. portfolio_changed, manual_refresh, initial_creation', max_length=100)),
                ('recalculation_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('review_required_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'catalog_buyer_compatibility_projection',
                'indexes': [models.Index(fields=['buyer_reference', 'status'], name='catalog_buy_buyer_r_031ba0_idx')],
                'unique_together': {('buyer_reference', 'company_scope_reference', 'buyer_entity_reference')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_type', models.CharField(choices=[('accessory', 'Accessory'), ('branded_merchandise', 'Branded Merchandise'), ('device', 'Device (reference only)')], max_length=30)),
                ('vendor_company_reference', models.UUIDField(db_index=True, help_text='Tenant Company vendor ID')),
                ('company_scope_reference', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=300)),
                ('sku', models.CharField(db_index=True, max_length=200)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('selling_status', models.CharField(choices=[('not_for_sale', 'Not For Sale'), ('for_sale', 'For Sale'), ('stop_selling', 'Stop Selling')], default='not_for_sale', max_length=20)),
                ('vendor_wholesale_price_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('vendor_wholesale_price_currency', models.CharField(default='USD', max_length=3)),
                ('primary_image_reference', models.UUIDField(blank=True, null=True)),
                ('media_references', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'catalog_product',
                'indexes': [models.Index(fields=['product_type', 'status', 'selling_status'], name='catalog_pro_product_a3cbc0_idx'), models.Index(fields=['vendor_company_reference', 'status'], name='catalog_pro_vendor__d7013f_idx'), models.Index(fields=['sku'], name='catalog_pro_sku_2c4c34_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductCompatibilityAssertion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_reference', models.UUIDField(db_index=True, help_text='Device ID from Device Catalog')),
                ('capability_evidence_snapshot_reference', models.UUIDField(blank=True, help_text='DeviceCapabilityEvidence ID at time of assertion — snapshot reference only', null=True)),
                ('is_compatible', models.BooleanField()),
                ('compatibility_basis', models.CharField(help_text='feature_evidence | manual_assertion | imported | review_required', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('asserted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('asserted_by_reference', models.UUIDField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compatibility_assertions', to='catalog.product')),
            ],
            options={
                'db_table': 'catalog_product_compatibility',
                'unique_together': {('product', 'device_reference')},
            },
        ),
    ]
