# Generated by Django 5.0.6 on 2026-06-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_color_product_height_product_inventory_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_threshold',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(blank=True, choices=[('Cases', 'Cases'), ('Screen Protection', 'Screen Protection'), ('Headphones', 'Headphones'), ('Speakers', 'Speakers'), ('Chargers and Cables', 'Chargers and Cables'), ('Memory', 'Memory'), ('Wearable Tech', 'Wearable Tech'), ('Phone Attachments', 'Phone Attachments')], max_length=50, null=True),
        ),
    ]
