# Generated by Django 5.0.6 on 2026-06-18 17:14

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_inventory_threshold_product_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicDropdownConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(db_index=True, help_text="e.g. 'color', 'product_type', 'product_category', 'company_status', 'company_type'", max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'catalog_dynamic_dropdown_config',
                'unique_together': {('field_name', 'value')},
            },
        ),
    ]
