# Generated by Django 5.0.6 on 2026-06-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_populate_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='eol_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived'), ('eol', 'EOL')], default='draft', max_length=20),
        ),
    ]
