# Generated by Django 5.0.6 on 2026-06-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_populate_brands_and_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived'), ('eol', 'EOL'), ('out_of_stock', 'Out of Stock')], default='draft', max_length=20),
        ),
    ]
