# Generated by Django 5.0.6 on 2026-06-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bluetooth_compatibility',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='compatibility_status',
            field=models.CharField(default='incomplete', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='compatible_charging_interface',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='compatible_watch_case_size',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='headphone_jack_compatibility',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='memory_capacity',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_expansion_compatibility',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='wireless_charging_compatibility',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productcompatibilityassertion',
            name='exclusion_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='productcompatibilityassertion',
            name='is_excluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productcompatibilityassertion',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
