# Generated by Django 5.0.6 on 2026-06-21 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_bluetooth_compatibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcompatibilityassertion',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productcompatibilityassertion',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcompatibilityassertion',
            name='device_launch_date_at_mapping',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcompatibilityassertion',
            name='device_status_at_mapping',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productcompatibilityassertion',
            name='exclusion_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcompatibilityassertion',
            name='exclusion_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productcompatibilityassertion',
            name='match_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productcompatibilityassertion',
            name='match_source',
            field=models.CharField(default='Auto-Mapped', max_length=50),
        ),
        migrations.AddField(
            model_name='productcompatibilityassertion',
            name='match_status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='productcompatibilityassertion',
            name='reviewed_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcompatibilityassertion',
            name='reviewed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcompatibilityassertion',
            name='sku',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productcompatibilityassertion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productcompatibilityassertion',
            name='updated_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcompatibilityassertion',
            name='vendor_company_reference',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
