# Generated by Django 5.0.6 on 2026-06-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_productcompatibilityassertion_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicdropdownconfig',
            name='accessory_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dynamicdropdownconfig',
            name='compatibility_mode',
            field=models.CharField(default='feature_based', max_length=20),
        ),
        migrations.AddField(
            model_name='dynamicdropdownconfig',
            name='compatibility_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dynamicdropdownconfig',
            name='eligible_device_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dynamicdropdownconfig',
            name='match_logic',
            field=models.CharField(default='OR', max_length=50),
        ),
        migrations.AddField(
            model_name='dynamicdropdownconfig',
            name='status',
            field=models.CharField(default='setup_required', max_length=20),
        ),
    ]
