# Generated by Django 5.0.6 on 2026-06-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_dynamicdropdownconfig_accessory_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
