# Generated by Django 5.0.6 on 2026-07-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_activate_default_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deactivation_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
