# Generated by Django 5.0.6 on 2026-08-01 08:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_product_deactivation_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProductExportDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_reference', models.UUIDField(db_index=True)),
                ('company_scope_reference', models.UUIDField(db_index=True)),
                ('buyer_entity_reference', models.UUIDField(db_index=True)),
                ('exported_at', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exported_dates', to='catalog.product')),
            ],
            options={
                'db_table': 'catalog_buyer_product_exported_date',
                'indexes': [models.Index(fields=['company_scope_reference', 'product'], name='catalog_buy_company_bac888_idx')],
                'unique_together': {('buyer_reference', 'company_scope_reference', 'buyer_entity_reference', 'product')},
            },
        ),
    ]
