# Generated by Django 5.0.6 on 2026-08-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_buyerproductexportdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerproductexportjob',
            name='failure_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyerproductexportjob',
            name='trigger_type',
            field=models.CharField(choices=[('USER', 'User'), ('SYSTEM', 'System')], default='USER', max_length=10),
        ),
        migrations.AddField(
            model_name='buyerproductexportjob',
            name='triggered_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyerproductexportjob',
            name='triggered_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='buyerproductexportjob',
            name='triggered_by_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyerproductexportselectionsnapshot',
            name='exported_products_snapshot',
            field=models.JSONField(blank=True, help_text='Immutable JSON snapshot of products: [{product_id, vendor_name, primary_image_url, product_name, sku, upc}]', null=True),
        ),
        migrations.AlterField(
            model_name='buyerproductexportjob',
            name='format',
            field=models.CharField(default='API', help_text='API | csv | json | xlsx', max_length=20),
        ),
        migrations.AlterField(
            model_name='buyerproductexportjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('processing', 'Processing'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with Errors'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('canceled', 'Canceled')], default='pending', max_length=30),
        ),
    ]
