# Generated by Django 5.0.6 on 2026-10-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_buyerproductexportjob_failure_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compatible_device_types',
            field=models.JSONField(blank=True, default=list, help_text="Device-type codes this product universally supports (e.g. ['phone', 'tablet']). Auto-mapped to every current and future device of those types."),
        ),
    ]
