# Generated by Django 5.0.6 on 2026-06-01 13:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalActionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_module', models.CharField(max_length=100)),
                ('action_type', models.CharField(help_text='e.g. quickbooks_invoice_post, vendor_order_export, sftp_upload', max_length=100)),
                ('source_record_id', models.UUIDField(db_index=True)),
                ('payload_reference', models.JSONField(default=dict, help_text='Sanitized payload for the external action — no sensitive data in plaintext')),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'integration_external_action_request',
            },
        ),
        migrations.CreateModel(
            name='ExternalActionOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome_status', models.CharField(help_text='success | failed | partial | timed_out | rejected_by_external', max_length=30)),
                ('external_reference_id', models.CharField(blank=True, help_text="External system's ID for this action — stored as reference only", max_length=500)),
                ('response_summary', models.JSONField(default=dict)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outcome', to='integration.externalactionrequest')),
            ],
            options={
                'db_table': 'integration_external_action_outcome',
            },
        ),
        migrations.CreateModel(
            name='ExternalConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_scope_reference', models.UUIDField(db_index=True)),
                ('connector_type', models.CharField(choices=[('quickbooks', 'QuickBooks'), ('sftp', 'SFTP'), ('rest_api', 'REST API'), ('webhook', 'Webhook'), ('email', 'Email'), ('manual', 'Manual'), ('csv', 'CSV File')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('config_reference', models.CharField(blank=True, help_text='Vault key or encrypted config reference — NOT raw credentials', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'integration_external_connection',
                'indexes': [models.Index(fields=['company_scope_reference', 'connector_type', 'status'], name='integration_company_a7b863_idx')],
            },
        ),
        migrations.AddField(
            model_name='externalactionrequest',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_requests', to='integration.externalconnection'),
        ),
        migrations.CreateModel(
            name='ExternalIdMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cixci_module', models.CharField(max_length=100)),
                ('cixci_record_type', models.CharField(max_length=150)),
                ('cixci_record_id', models.UUIDField(db_index=True)),
                ('external_id', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='id_mappings', to='integration.externalconnection')),
            ],
            options={
                'db_table': 'integration_external_id_mapping',
                'unique_together': {('connection', 'cixci_record_id')},
            },
        ),
        migrations.CreateModel(
            name='InboundWebhookReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_event_id', models.CharField(db_index=True, max_length=500)),
                ('event_type', models.CharField(max_length=200)),
                ('signature_verified', models.BooleanField(default=False)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('processing_status', models.CharField(default='received', help_text='received | processing | processed | failed | ignored', max_length=30)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_receipts', to='integration.externalconnection')),
            ],
            options={
                'db_table': 'integration_inbound_webhook_receipt',
                'unique_together': {('connection', 'provider_event_id')},
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=200)),
                ('payload_hash', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_flight', 'In Flight'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('superseded', 'Superseded')], default='pending', max_length=20)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_response_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255)),
                ('is_redacted', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_deliveries', to='integration.externalconnection')),
            ],
            options={
                'db_table': 'integration_webhook_delivery',
                'indexes': [models.Index(fields=['event_type', 'status'], name='integration_event_t_c9a555_idx')],
            },
        ),
    ]
