# Generated by Django 5.0.6 on 2026-06-01 13:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('model_number', models.CharField(blank=True, db_index=True, max_length=200)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=200)),
                ('lifecycle_status', models.CharField(choices=[('announced', 'Announced'), ('available', 'Available'), ('current', 'Current'), ('legacy', 'Legacy'), ('eol', 'End of Life'), ('retired', 'Retired')], default='announced', max_length=20)),
                ('announced_date', models.DateField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('eol_date', models.DateField(blank=True, null=True)),
                ('image_readiness_reference', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_by', models.UUIDField(blank=True, help_text='System Admin actor reference', null=True)),
            ],
            options={
                'db_table': 'device_device',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'device_type',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('company_reference', models.UUIDField(blank=True, help_text='Tenant Company reference if onboarded', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'device_manufacturer',
            },
        ),
        migrations.CreateModel(
            name='BuyerDevicePortfolioSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_reference', models.UUIDField(db_index=True)),
                ('company_scope_reference', models.UUIDField(db_index=True)),
                ('buyer_entity_reference', models.UUIDField(db_index=True)),
                ('device_ids', models.JSONField(help_text='List of Device IDs at snapshot time')),
                ('device_count', models.PositiveIntegerField()),
                ('triggered_by_change_record', models.UUIDField(blank=True, null=True)),
                ('snapshot_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'device_buyer_portfolio_snapshot',
                'indexes': [models.Index(fields=['buyer_reference', 'company_scope_reference', 'created_at'], name='device_buye_buyer_r_c727e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='BuyerDevicePortfolioReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_reference', models.UUIDField(db_index=True, help_text='User ID')),
                ('company_scope_reference', models.UUIDField(db_index=True)),
                ('buyer_entity_reference', models.UUIDField(db_index=True)),
                ('active_flag', models.BooleanField(db_index=True, default=True)),
                ('change_source', models.CharField(choices=[('buyer_action', 'Buyer Action'), ('admin_on_behalf', 'Admin On Behalf'), ('service_identity_sync', 'Service Identity Sync'), ('system_correction', 'System Correction')], max_length=30)),
                ('last_change_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_portfolio_snapshot_reference', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_references', to='devices.device')),
            ],
            options={
                'db_table': 'device_buyer_portfolio_reference',
            },
        ),
        migrations.CreateModel(
            name='BuyerDevicePortfolioChangeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_reference', models.UUIDField(db_index=True)),
                ('company_scope_reference', models.UUIDField(db_index=True)),
                ('buyer_entity_reference', models.UUIDField(db_index=True)),
                ('change_type', models.CharField(choices=[('device_added', 'Device Added'), ('device_removed', 'Device Removed'), ('device_reactivated', 'Device Reactivated'), ('device_deactivated', 'Device Deactivated'), ('portfolio_reset', 'Portfolio Reset'), ('admin_correction', 'Admin Correction'), ('service_sync', 'Service Identity Sync'), ('system_correction', 'System Correction')], max_length=30)),
                ('change_source', models.CharField(choices=[('buyer_action', 'Buyer Action'), ('admin_on_behalf', 'Admin On Behalf'), ('service_identity_sync', 'Service Identity Sync'), ('system_correction', 'System Correction')], max_length=30)),
                ('actor_reference', models.UUIDField(blank=True, null=True)),
                ('service_trigger_reference', models.CharField(blank=True, max_length=200)),
                ('actor_is_admin_on_behalf', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('portfolio_reference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_records', to='devices.buyerdeviceportfolioreference')),
                ('resulting_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='devices.buyerdeviceportfoliosnapshot')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.device')),
            ],
            options={
                'db_table': 'device_buyer_portfolio_change_record',
            },
        ),
        migrations.CreateModel(
            name='DeviceCapabilityEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_snapshot', models.JSONField(help_text='Dict of {feature_group_code: feature_value_code} at generation time')),
                ('profile_compliance', models.CharField(default='unknown', help_text='compliant | non_compliant | review_required | unknown', max_length=30)),
                ('non_compliant_groups', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('generation_triggered_by', models.CharField(blank=True, max_length=100)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='capability_evidence', to='devices.device')),
            ],
            options={
                'db_table': 'device_capability_evidence',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='devices.devicetype'),
        ),
        migrations.CreateModel(
            name='FeatureGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('lifecycle', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('retired', 'Retired')], default='draft', max_length=15)),
                ('is_required_for_compatibility', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feature_groups', to='devices.devicetype')),
            ],
            options={
                'db_table': 'device_feature_group',
            },
        ),
        migrations.CreateModel(
            name='DeviceCapabilityProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requirement_level', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('unsupported', 'Unsupported'), ('review_required', 'Review Required')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('superseded', 'Superseded'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capability_profiles', to='devices.devicetype')),
                ('feature_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.featuregroup')),
            ],
            options={
                'db_table': 'device_capability_profile',
            },
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=200)),
                ('code', models.SlugField(max_length=100)),
                ('lifecycle', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('retired', 'Retired')], default='draft', max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('feature_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='devices.featuregroup')),
            ],
            options={
                'db_table': 'device_feature_value',
            },
        ),
        migrations.CreateModel(
            name='DeviceFeatureAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_override', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True)),
                ('override_actor_reference', models.UUIDField(blank=True, null=True)),
                ('audit_record_reference', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feature_assignments', to='devices.device')),
                ('feature_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.featuregroup')),
                ('feature_value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.featurevalue')),
            ],
            options={
                'db_table': 'device_feature_assignment',
            },
        ),
        migrations.CreateModel(
            name='CompatibilityMarker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_attribute', models.CharField(help_text='Raw field name from CSV', max_length=200)),
                ('raw_value', models.CharField(help_text='Raw value from CSV', max_length=500)),
                ('normalization_status', models.CharField(default='pending', help_text='pending | suggested | confirmed | rejected | abandoned', max_length=30)),
                ('import_job_reference', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compatibility_markers', to='devices.device')),
                ('normalized_feature_group', models.ForeignKey(blank=True, help_text='Set when normalization is suggested/confirmed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.featuregroup')),
                ('normalized_feature_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.featurevalue')),
            ],
            options={
                'db_table': 'device_compatibility_marker',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='devices.manufacturer'),
        ),
        migrations.CreateModel(
            name='SuggestedNormalization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='pending', help_text='pending | accepted | rejected | overridden', max_length=30)),
                ('accepted_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('compatibility_marker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normalizations', to='devices.compatibilitymarker')),
                ('resulting_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='devices.devicefeatureassignment')),
                ('suggested_feature_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.featuregroup')),
                ('suggested_feature_value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.featurevalue')),
            ],
            options={
                'db_table': 'device_suggested_normalization',
            },
        ),
        migrations.CreateModel(
            name='DataQualityException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exception_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('unresolved', 'Unresolved')], default='created', max_length=20)),
                ('review_actor_reference', models.UUIDField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('compatibility_marker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='devices.compatibilitymarker')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dqe_records', to='devices.device')),
            ],
            options={
                'db_table': 'device_data_quality_exception',
                'indexes': [models.Index(fields=['status', 'created_at'], name='device_data_status_c8637d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='buyerdeviceportfolioreference',
            index=models.Index(fields=['buyer_reference', 'company_scope_reference', 'active_flag'], name='device_buye_buyer_r_5c79a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='buyerdeviceportfolioreference',
            unique_together={('device', 'buyer_reference', 'company_scope_reference', 'buyer_entity_reference')},
        ),
        migrations.AddIndex(
            model_name='buyerdeviceportfoliochangerecord',
            index=models.Index(fields=['buyer_reference', 'company_scope_reference', 'created_at'], name='device_buye_buyer_r_320260_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='featuregroup',
            unique_together={('device_type', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='devicecapabilityprofile',
            unique_together={('device_type', 'feature_group', 'status')},
        ),
        migrations.AlterUniqueTogether(
            name='featurevalue',
            unique_together={('feature_group', 'code')},
        ),
        migrations.AddIndex(
            model_name='devicefeatureassignment',
            index=models.Index(fields=['device', 'feature_group', 'is_active'], name='device_feat_device__05d595_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['lifecycle_status'], name='device_devi_lifecyc_175007_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['manufacturer', 'device_type'], name='device_devi_manufac_5904bb_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['model_number'], name='device_devi_model_n_bdfe4b_idx'),
        ),
    ]
