# Generated by Django 5.0.6 on 2026-06-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='bluetooth_compatibility',
            field=models.CharField(blank=True, default='Yes', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='compatible_charging_interface',
            field=models.CharField(blank=True, default='Not Compatible', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='compatible_watch_case_size',
            field=models.CharField(blank=True, default='Not Compatible', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='headphone_jack_compatibility',
            field=models.CharField(blank=True, default='Not Compatible', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='maximum_supported_storage',
            field=models.CharField(blank=True, default='Not Compatible', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='storage_expansion_compatibility',
            field=models.CharField(blank=True, default='Not Compatible', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='wireless_charging_compatibility',
            field=models.CharField(blank=True, default='Not Compatible', max_length=100),
        ),
    ]
