# Generated by Django 5.0.6 on 2026-06-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_bluetooth_compatibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='auto_mapping_eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='compatibility_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='status',
            field=models.CharField(default='setup_required', max_length=20),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='supported_accessory_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='device',
            name='lifecycle_status',
            field=models.CharField(choices=[('announced', 'Announced'), ('available', 'Available'), ('current', 'Current'), ('legacy', 'Legacy'), ('eol', 'End of Life'), ('retired', 'Retired'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='available', max_length=20),
        ),
    ]
