# Generated by Django 5.0.6 on 2026-09-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='lifecycle_status',
            field=models.CharField(choices=[('available', 'Available'), ('launching', 'Launching'), ('inactive', 'Inactive'), ('eol', 'EOL'), ('announced', 'Announced'), ('current', 'Current'), ('legacy', 'Legacy'), ('retired', 'Retired'), ('archived', 'Archived')], default='available', max_length=20),
        ),
    ]
