# Generated by Django 5.0.6 on 2026-06-01 13:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySummaryConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('retired', 'Retired')], default='active', max_length=20)),
                ('delivery_times', models.JSONField(help_text='List of HH:MM times in schedule_timezone')),
                ('schedule_timezone', models.CharField(default='UTC', max_length=50)),
                ('skip_weekends', models.BooleanField(default=False)),
                ('skip_holidays', models.BooleanField(default=False)),
                ('explicit_recipient_ids', models.JSONField(default=list)),
                ('last_successful_summary_cursor_reference', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(help_text='Must be CIXCI System Admin')),
            ],
            options={
                'db_table': 'notification_activity_summary_config',
            },
        ),
        migrations.CreateModel(
            name='ActivitySummaryDeliveryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporting_window_reference', models.UUIDField(help_text='Analytics ActivitySummaryReportingWindow ID')),
                ('aggregation_record_reference', models.UUIDField(help_text='Analytics ActivitySummaryAggregationRecord ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('acknowledged', 'Acknowledged (transport-layer only)'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('effective_recipient_ids', models.JSONField(default=list)),
                ('provider_response_reference', models.JSONField(default=dict)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_attempts', to='notification.activitysummaryconfiguration')),
            ],
            options={
                'db_table': 'notification_summary_delivery_attempt',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('user', 'User'), ('entity', 'Entity'), ('company', 'Company')], max_length=10)),
                ('scope_id', models.UUIDField(db_index=True, help_text='User ID, Entity ID, or Company ID')),
                ('event_type', models.CharField(blank=True, help_text='Blank = all events', max_length=200)),
                ('channel', models.CharField(blank=True, choices=[('email', 'Email'), ('in_app', 'In-App'), ('sms', 'SMS (placeholder)'), ('webhook', 'Webhook / External (placeholder)'), ('push', 'Push Notification (placeholder)')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('use_digest', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('is_unsubscribed', models.BooleanField(default=False)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_preference',
                'indexes': [models.Index(fields=['scope_id', 'event_type', 'channel'], name='notificatio_scope_i_ce0e5e_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=200)),
                ('source_module', models.CharField(max_length=100)),
                ('source_record_id', models.UUIDField(blank=True, null=True)),
                ('safe_payload_summary', models.JSONField(default=dict)),
                ('requested_recipient_ids', models.JSONField(default=list)),
                ('company_scope_reference', models.UUIDField(db_index=True)),
                ('template_code', models.CharField(blank=True, max_length=150)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App'), ('sms', 'SMS (placeholder)'), ('webhook', 'Webhook / External (placeholder)'), ('push', 'Push Notification (placeholder)')], default='email', max_length=20)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('preference_outcome', models.CharField(blank=True, choices=[('send', 'Send'), ('block', 'Block'), ('delay', 'Delay'), ('digest', 'Digest'), ('review_required', 'Review Required'), ('suppress', 'Suppress')], max_length=20, null=True)),
                ('preference_evaluation_detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'notification_request',
                'indexes': [models.Index(fields=['event_type', 'company_scope_reference', 'created_at'], name='notificatio_event_t_17cf96_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_code', models.CharField(db_index=True, max_length=150)),
                ('version', models.PositiveIntegerField(default=1)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App'), ('sms', 'SMS (placeholder)'), ('webhook', 'Webhook / External (placeholder)'), ('push', 'Push Notification (placeholder)')], max_length=20)),
                ('event_type', models.CharField(help_text='Source event that triggers this template', max_length=200)),
                ('subject_template', models.CharField(blank=True, max_length=500)),
                ('body_template', models.TextField()),
                ('dynamic_fields', models.JSONField(default=list, help_text='Safe field names allowed in template rendering')),
                ('redaction_rules', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('locale', models.CharField(default='en', max_length=10)),
                ('company_scope', models.UUIDField(blank=True, help_text='Null = platform-wide template', null=True)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_template',
                'indexes': [models.Index(fields=['event_type', 'channel', 'status'], name='notificatio_event_t_d4c2a7_idx')],
                'unique_together': {('template_code', 'version', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='RecipientResolutionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resolved_recipient_ids', models.JSONField(default=list)),
                ('excluded_recipient_ids', models.JSONField(default=list, help_text='Inactive, suppressed, or cross-tenant excluded')),
                ('role_expansion_snapshot', models.JSONField(default=dict)),
                ('max_recipients_cap', models.PositiveIntegerField(default=500)),
                ('cross_tenant_denied', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recipient_resolution', to='notification.notificationrequest')),
            ],
            options={
                'db_table': 'notification_recipient_resolution',
            },
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_id', models.UUIDField(db_index=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App'), ('sms', 'SMS (placeholder)'), ('webhook', 'Webhook / External (placeholder)'), ('push', 'Push Notification (placeholder)')], max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('suppressed', 'Suppressed'), ('delayed', 'Delayed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('superseded', 'Superseded')], default='requested', max_length=20)),
                ('provider_name', models.CharField(blank=True, max_length=100)),
                ('provider_message_id', models.CharField(blank=True, max_length=500)),
                ('provider_response_reference', models.JSONField(default=dict)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notification_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_attempts', to='notification.notificationrequest')),
            ],
            options={
                'db_table': 'notification_delivery_attempt',
                'indexes': [models.Index(fields=['recipient_id', 'status'], name='notificatio_recipie_8261bc_idx'), models.Index(fields=['notification_request', 'attempt_number'], name='notificatio_notific_5971d0_idx')],
            },
        ),
    ]
