# Generated by Django 5.0.6 on 2026-07-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrequest',
            name='attachments',
            field=models.JSONField(blank=True, default=list, help_text='List of dicts containing filename, content (base64), and mime_type'),
        ),
    ]
