# Generated by Django 5.0.6 on 2026-08-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_inappnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='inappnotification',
            name='audit_reference',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='classification',
            field=models.CharField(choices=[('REQUIRED_OPERATIONAL', 'Required Operational'), ('CONFIGURABLE_OPERATIONAL', 'Configurable Operational'), ('INFORMATIONAL', 'Informational'), ('ADMIN_SYSTEM_CRITICAL', 'Admin System Critical'), ('DASHBOARD_ONLY', 'Dashboard Only'), ('API_ONLY', 'API Only'), ('OPERATIONAL_FILE_DELIVERY', 'Operational File Delivery')], default='INFORMATIONAL', max_length=50),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='delivery_attempt_reference',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='delivery_mode',
            field=models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('DAILY_DIGEST', 'Daily Digest'), ('DAILY_SUMMARY', 'Daily Summary'), ('SCHEDULED_SUMMARY', 'Scheduled Summary'), ('DASHBOARD', 'Dashboard'), ('API', 'API'), ('OPERATIONAL_FILE', 'Operational File'), ('NONE', 'None')], default='IMMEDIATE', max_length=50),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='source_module',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='source_record_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationrequest',
            name='classification',
            field=models.CharField(choices=[('REQUIRED_OPERATIONAL', 'Required Operational'), ('CONFIGURABLE_OPERATIONAL', 'Configurable Operational'), ('INFORMATIONAL', 'Informational'), ('ADMIN_SYSTEM_CRITICAL', 'Admin System Critical'), ('DASHBOARD_ONLY', 'Dashboard Only'), ('API_ONLY', 'API Only'), ('OPERATIONAL_FILE_DELIVERY', 'Operational File Delivery')], default='CONFIGURABLE_OPERATIONAL', max_length=50),
        ),
    ]
