# Generated by Django 5.0.6 on 2026-08-11 10:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_inappnotification_audit_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryattempt',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('suppressed', 'Suppressed'), ('delayed', 'Delayed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('superseded', 'Superseded'), ('retry_scheduled', 'Retry Scheduled'), ('retry_exhausted', 'Retry Exhausted'), ('review_required', 'Review Required')], default='requested', max_length=20),
        ),
        migrations.CreateModel(
            name='SLAReminderChain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sla_chain_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('source_module', models.CharField(max_length=100)),
                ('source_condition_reference', models.UUIDField(db_index=True)),
                ('company_scope_reference', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(max_length=200)),
                ('reminder_sequence', models.PositiveIntegerField(default=1)),
                ('first_threshold_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_reminder_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_reminder_due_at', models.DateTimeField(blank=True, null=True)),
                ('chain_status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('superseded', 'Superseded'), ('exhausted', 'Exhausted')], db_index=True, default='active', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_reference', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_reminder_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsequent_reminders', to='notification.slareminderchain')),
            ],
            options={
                'db_table': 'notification_sla_reminder_chain',
                'indexes': [models.Index(fields=['source_condition_reference', 'chain_status'], name='notificatio_source__23bd09_idx'), models.Index(fields=['company_scope_reference', 'chain_status'], name='notificatio_company_93326e_idx')],
            },
        ),
    ]
