# Generated by Django 5.0.6 on 2026-06-01 13:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('product_image', 'Product Image'), ('device_image', 'Device Image'), ('brand_logo', 'Brand Logo'), ('document', 'Document'), ('video', 'Video (placeholder)'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('upload_pending', 'Upload Pending'), ('uploading', 'Uploading'), ('validating', 'Validating'), ('validation_failed', 'Validation Failed'), ('processing', 'Processing'), ('processing_failed', 'Processing Failed'), ('ready', 'Ready'), ('restricted', 'Restricted'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('superseded', 'Superseded')], default='upload_pending', max_length=30)),
                ('owner_module', models.CharField(help_text='Which module owns this asset (e.g. catalog, devices)', max_length=100)),
                ('owner_record_id', models.UUIDField(blank=True, help_text='ID of owning record (Product, Device, etc.)', null=True)),
                ('company_scope_reference', models.UUIDField(db_index=True)),
                ('original_filename', models.CharField(max_length=500)),
                ('file_extension', models.CharField(max_length=20)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('storage_key', models.CharField(blank=True, help_text='S3/R2 object key', max_length=1000)),
                ('storage_provider', models.CharField(default='s3', max_length=50)),
                ('content_hash', models.CharField(blank=True, max_length=512)),
                ('is_public', models.BooleanField(default=False)),
                ('access_policy', models.JSONField(default=dict)),
                ('uploaded_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'media_asset',
                'indexes': [models.Index(fields=['owner_module', 'owner_record_id'], name='media_asset_owner_m_81d58e_idx'), models.Index(fields=['company_scope_reference', 'asset_type', 'status'], name='media_asset_company_4b2141_idx')],
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='initiated', max_length=20)),
                ('presigned_url', models.URLField(blank=True, max_length=2000)),
                ('expected_filename', models.CharField(max_length=500)),
                ('expected_mime_type', models.CharField(max_length=100)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.UUIDField()),
                ('company_scope_reference', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='upload_sessions', to='media.mediaasset')),
            ],
            options={
                'db_table': 'media_upload_session',
            },
        ),
        migrations.CreateModel(
            name='MediaAssetVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('is_current', models.BooleanField(default=True)),
                ('storage_key', models.CharField(max_length=1000)),
                ('content_hash', models.CharField(max_length=512)),
                ('file_size_bytes', models.PositiveBigIntegerField()),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='media.mediaasset')),
            ],
            options={
                'db_table': 'media_asset_version',
                'ordering': ['-version_number'],
                'unique_together': {('asset', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='Rendition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rendition_type', models.CharField(help_text='e.g. thumbnail_200, webp_800, original', max_length=50)),
                ('storage_key', models.CharField(max_length=1000)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('is_ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renditions', to='media.mediaasset')),
            ],
            options={
                'db_table': 'media_rendition',
                'unique_together': {('asset', 'rendition_type')},
            },
        ),
    ]
