# Generated by Django 5.0.6 on 2026-06-01 13:56

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaunchEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_scope_reference', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planning', 'Planning'), ('readiness_check', 'Readiness Check'), ('blocked', 'Blocked'), ('ready', 'Ready'), ('launched', 'Launched'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed'), ('post_launch_review', 'Post-Launch Review'), ('closed', 'Closed')], default='draft', max_length=30)),
                ('target_launch_date', models.DateField(blank=True, null=True)),
                ('product_readiness_references', models.JSONField(default=list)),
                ('device_readiness_references', models.JSONField(default=list)),
                ('pricing_readiness_references', models.JSONField(default=list)),
                ('notification_trigger_references', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'launch_event',
                'indexes': [models.Index(fields=['company_scope_reference', 'status'], name='launch_even_company_10b7cf_idx')],
            },
        ),
    ]
